export const courses = [
  {
    id: 1,
    title: "IT Statistics Data Science And Business Analysis",
    category: "Digital Marketing",
    rating: 4.5,
    price: 50,
    lessons: 10,
    duration: "19h 30m",
    students: "20+",
    instructor: "Samantha",
    image: "/images/image (6).svg",
    thumbnail: "/images/Container.svg",
  },
  {
    id: 2,
    title: "Bilginer Adobe Illustrator For Graphic Design",
    category: "Digital Marketing",
    rating: 4.5,
    price: 50,
    lessons: 10,
    duration: "19h 30m",
    students: "20+",
    instructor: "Charles",
    image: "/images/image (8).svg",
    thumbnail: "/images/Link (1).svg",
  },
  {
    id: 3,
    title: "Starting SEO As Your Home Based Business",
    category: "Digital Marketing",
    rating: 4.5,
    price: 50,
    lessons: 10,
    duration: "19h 30m",
    students: "20+",
    instructor: "Morgan",
    image: "/images/image (9).svg",
    thumbnail: "/images/Link (2).svg",
  },
  {
    id: 4,
    title: "Bilginer Adobe Illustrator For Graphic Design",
    category: "Digital Marketing",
    rating: 4.5,
    price: 50,
    lessons: 10,
    duration: "19h 30m",
    students: "20+",
    instructor: "Brian Brewer",
    image: "/images/image (10).svg",
    thumbnail: "/images/Link (2).svg",
  },
  {
    id: 5,
    title: "IT Statistics Data Science And Business Analysis",
    category: "Digital Marketing",
    rating: 4.5,
    price: 50,
    lessons: 10,
    duration: "19h 30m",
    students: "20+",
    instructor: "Rodriguez",
    image: "/images/image (11).svg",
    thumbnail: "/images/Link (3).svg",
  },
  {
    id: 6,
    title: "Starting SEO As Your Home Based Business",
    category: "Digital Marketing",
    rating: 4.5,
    price: 50,
    lessons: 10,
    duration: "19h 30m",
    students: "20+",
    instructor: "Morgan",
    image: "/images/image (12).svg",
    thumbnail: "/images/Container (1).svg",
  },
];
